name: OKX Equity Monitor

on:
  schedule:
    - cron: "*/15 * * * *"  # 每15分钟运行一次（UTC时间）→ 北京时间：每小时的 0、15、30、45 分
  workflow_dispatch:        # 支持手动触发测试

jobs:
  monitor:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the monitor script
        env:
          OKX_API_KEY: ${{ secrets.OKX_API_KEY }}
          OKX_SECRET_KEY: ${{ secrets.OKX_SECRET_KEY }}
          OKX_PASSPHRASE: ${{ secrets.OKX_PASSPHRASE }}
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
        run: |
          python main.py

  notify-on-failure:
    needs: monitor
    if: failure()
    runs-on: ubuntu-22.04
    steps:
      - name: Send failure notification
        run: |
          curl -X POST "${{ secrets.WECHAT_WEBHOOK }}" \
            -H 'Content-Type: application/json' \
            -d '{"msgtype":"text","text":{"content":"❌ GitHub Actions 运行失败，请及时检查！"}}'
